### ISSUE TITLE
Door/Window opening for two sided windows

### ISSUE THREAD

**Issue by Zerogiven** [shmuelzon/home-assistant-floor-plan#20]
Hi,

First at all, much thanks for your plugin, great done! :)

Is there any way to define two sided windows with one object in sh3d? maybe by a naming convention (e.g.: binary_sensor.kuche_fenster_links_contact;binary_sensor.kuche_fenster_rechts_contact) :)

thanks again,
cheers
Chris

**Comment by shmuelzon** [comment]
Hey,

For this to work, I'd first need to figure out this item from my To-Do list: `Make sure state-icons/labels do not overlap` since the window would still have one location in SH3D and that's where I'd try to place both icons.
I'm not exactly sure what algorithm/logic to use in order to properly implement that but, once done, implementing this request should be simple enough.
