### ISSUE TITLE
Hide the ceiling light icons when rendering the image

### ISSUE THREAD

**Issue by rushabh31** [shmuelzon/home-assistant-floor-plan#84]
**Question**
Currently, when rendering an image in our application, the ceiling light icons are visible in the output. This may cause distractions or interfere with the visual quality of the rendered images, especially in scenarios where ceiling lights are not relevant to the user's view.

Is there a way to hide the ceiling light icons when the lights of that room is not on in the render?

**Comment by shmuelzon** [comment]
Hey, I'm not sure I totally follow our scenario as it sounds to me like multiple questions.
If you want to hide a light icon, you can click it in the detected lights list of the plugin and, for the display type, choose "None".
This will, however, always hide the icon. Is that what you need or are you looking for something that will hide/show it according to the light state?

Then you ask about a light that's not in the render, what does that mean exactly? That it's on another floor or that it's just off camera? If it's the former, then the newer versions of this plugin take the level into consideration and only work on the lights that are in the same level that's currently viewed. If it's the latter, then the icons should also be placed off the image so you shouldn't see them either.

**Comment by cryptk** [comment]
I think they mean something that I would love to do as well.  I would like to be able to have some items not show in the render, but still exist in the floorplan.

An example of this are the lights on my front porch.  You can see them in the render as small circles and it looks a bit odd having a small circle just floating in space.  What would be nice is if there was a way to not render the light object itself, but still generate renders for the light that it casts.  That way I could have control over the lights on my front porch without having the tiny circles floating in space (which are the actual light objects in Sweet Home).

This might be a limitation of SH3D though because I'm pretty sure that the only way to not render an object would be to set it as invisible, but for lights, this will also prevent it from rendering the light that it casts.

**Comment by shmuelzon** [comment]
I thought @rushabh31 was referring to the clickable icons for toggling the lights but I haven't heard back since.

@cryptk SH3D must have a piece of furniture that emits light for it to render one as such. That's out of my control. However, if what you want is a light source without it appearing in the image, have you tried one of the "... light source" items? I think they don't show up in the render but do emit the light.

![image](https://github.com/user-attachments/assets/026cc25f-9943-43f1-a286-68da5f628860)

**Comment by rushabh31** [comment]
@shmuelzon I was actually referring to what @cryptk pointed out. I’d prefer not to have the small circle just floating in space icon shown in the render.

**Comment by shmuelzon** [comment]
@rushabh31, got it. Please try the light sources mentioned above and see if they do what you need. I'm afraid I don't have any other solution though as all the rendering is handled by SH3D and I can't really change it.

**Comment by rushabh31** [comment]
@shmuelzon That worked! Thanks :)

**Comment by shmuelzon** [comment]
Glad to hear. @cryptk hopefully this will work out for you too so I'm closing this ticket for now. Feel free to reopen it (or another) if there's still a problem.
