### ISSUE TITLE
Adding things that don't correspond to furniture

### ISSUE THREAD

**Issue by Daniel15** [shmuelzon/home-assistant-floor-plan#89]
I want to show the temperature of each room that I have a temperature sensor in, but don't want to have to manually modify the floor plan YAML to manually add it every time I update it. Since this doesn't correlate to a piece of furniture in Sweet Home 3D, what's the best way of doing it? Same thing with things like buttons.

Thanks for the awesome plugin.

**Comment by shmuelzon** [comment]
Hey, the simplest solution I can think of (and what I did for the temperature sensor in the README demo) it to just take a small piece of furniture, e.g., a camera, and give it the name of the `sensor.xxx`. It's small enough and will be covered with the sensor value anyway so it shouldn't interfere too much.

**Comment by cryptk** [comment]
@shmuelzon why not allow creating elements for objects that are not marked as visible? This would allow creating a placeholder object in the floorplan, named appropriately, which would create an element in the card, but it wouldn't show up in the render.

This may not make sense for light elements since marking them as not visible also removes any light that they may cast, but should be fine for anything that is not a light.

**Comment by shmuelzon** [comment]
@cryptk I don't want to steer away from the mechanics of SH3D too much but making invisible object visible or somehow adding elements to the floor plan that aren't part of the project.

As a workaround, I can suggest taking any piece of furniture from the list, change its size to something very, very small, and give it the name of the sensor/entity you want to show up in the floorplan. You won't have a big eyesore in the render but will have the label/icon at the relevant place in the floor plan.

**Comment by shmuelzon** [comment]
I'm closing this ticket for now due to the explanation above. I hope that workaround is good enough for now.
